// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trinity.proto
// Protobuf C++ Version: 6.33.1

#ifndef trinity_2eproto_2epb_2eh
#define trinity_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_trinity_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_trinity_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_trinity_2eproto;
}  // extern "C"
class GeoWeatherGate;
struct GeoWeatherGateDefaultTypeInternal;
extern GeoWeatherGateDefaultTypeInternal _GeoWeatherGate_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GeoWeatherGate_class_data_;
class TrinityLedger;
struct TrinityLedgerDefaultTypeInternal;
extern TrinityLedgerDefaultTypeInternal _TrinityLedger_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TrinityLedger_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class GeoWeatherGate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GeoWeatherGate) */ {
 public:
  inline GeoWeatherGate() : GeoWeatherGate(nullptr) {}
  ~GeoWeatherGate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GeoWeatherGate* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GeoWeatherGate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GeoWeatherGate(::google::protobuf::internal::ConstantInitialized);

  inline GeoWeatherGate(const GeoWeatherGate& from) : GeoWeatherGate(nullptr, from) {}
  inline GeoWeatherGate(GeoWeatherGate&& from) noexcept
      : GeoWeatherGate(nullptr, ::std::move(from)) {}
  inline GeoWeatherGate& operator=(const GeoWeatherGate& from) {
    CopyFrom(from);
    return *this;
  }
  inline GeoWeatherGate& operator=(GeoWeatherGate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GeoWeatherGate& default_instance() {
    return *reinterpret_cast<const GeoWeatherGate*>(
        &_GeoWeatherGate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GeoWeatherGate& a, GeoWeatherGate& b) { a.Swap(&b); }
  inline void Swap(GeoWeatherGate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GeoWeatherGate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GeoWeatherGate* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GeoWeatherGate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GeoWeatherGate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GeoWeatherGate& from) { GeoWeatherGate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GeoWeatherGate* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GeoWeatherGate"; }

  explicit GeoWeatherGate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GeoWeatherGate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GeoWeatherGate& from);
  GeoWeatherGate(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GeoWeatherGate&& from) noexcept
      : GeoWeatherGate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSensorIdFieldNumber = 5,
    kEntryHashFieldNumber = 6,
    kTemperatureFieldNumber = 1,
    kHumidityFieldNumber = 2,
    kTimestampFieldNumber = 4,
    kPressureFieldNumber = 3,
  };
  // string sensor_id = 5;
  void clear_sensor_id() ;
  const ::std::string& sensor_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_sensor_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_sensor_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_sensor_id();
  void set_allocated_sensor_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_sensor_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_sensor_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_sensor_id();

  public:
  // bytes entry_hash = 6;
  void clear_entry_hash() ;
  const ::std::string& entry_hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_entry_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_entry_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_entry_hash();
  void set_allocated_entry_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_entry_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_entry_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_entry_hash();

  public:
  // float temperature = 1;
  void clear_temperature() ;
  float temperature() const;
  void set_temperature(float value);

  private:
  float _internal_temperature() const;
  void _internal_set_temperature(float value);

  public:
  // float humidity = 2;
  void clear_humidity() ;
  float humidity() const;
  void set_humidity(float value);

  private:
  float _internal_humidity() const;
  void _internal_set_humidity(float value);

  public:
  // int64 timestamp = 4;
  void clear_timestamp() ;
  ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // float pressure = 3;
  void clear_pressure() ;
  float pressure() const;
  void set_pressure(float value);

  private:
  float _internal_pressure() const;
  void _internal_set_pressure(float value);

  public:
  // @@protoc_insertion_point(class_scope:GeoWeatherGate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 32,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GeoWeatherGate& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sensor_id_;
    ::google::protobuf::internal::ArenaStringPtr entry_hash_;
    float temperature_;
    float humidity_;
    ::int64_t timestamp_;
    float pressure_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_trinity_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GeoWeatherGate_class_data_;
// -------------------------------------------------------------------

class TrinityLedger final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TrinityLedger) */ {
 public:
  inline TrinityLedger() : TrinityLedger(nullptr) {}
  ~TrinityLedger() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrinityLedger* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrinityLedger));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrinityLedger(::google::protobuf::internal::ConstantInitialized);

  inline TrinityLedger(const TrinityLedger& from) : TrinityLedger(nullptr, from) {}
  inline TrinityLedger(TrinityLedger&& from) noexcept
      : TrinityLedger(nullptr, ::std::move(from)) {}
  inline TrinityLedger& operator=(const TrinityLedger& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrinityLedger& operator=(TrinityLedger&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrinityLedger& default_instance() {
    return *reinterpret_cast<const TrinityLedger*>(
        &_TrinityLedger_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TrinityLedger& a, TrinityLedger& b) { a.Swap(&b); }
  inline void Swap(TrinityLedger* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrinityLedger* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrinityLedger* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrinityLedger>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrinityLedger& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrinityLedger& from) { TrinityLedger::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrinityLedger* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TrinityLedger"; }

  explicit TrinityLedger(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TrinityLedger(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TrinityLedger& from);
  TrinityLedger(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TrinityLedger&& from) noexcept
      : TrinityLedger(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWeatherDataFieldNumber = 1,
  };
  // repeated .GeoWeatherGate weather_data = 1;
  int weather_data_size() const;
  private:
  int _internal_weather_data_size() const;

  public:
  void clear_weather_data() ;
  ::GeoWeatherGate* PROTOBUF_NONNULL mutable_weather_data(int index);
  ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>* PROTOBUF_NONNULL mutable_weather_data();

  private:
  const ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>& _internal_weather_data() const;
  ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>* PROTOBUF_NONNULL _internal_mutable_weather_data();
  public:
  const ::GeoWeatherGate& weather_data(int index) const;
  ::GeoWeatherGate* PROTOBUF_NONNULL add_weather_data();
  const ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>& weather_data() const;
  // @@protoc_insertion_point(class_scope:TrinityLedger)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TrinityLedger& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::GeoWeatherGate > weather_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_trinity_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TrinityLedger_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GeoWeatherGate

// float temperature = 1;
inline void GeoWeatherGate::clear_temperature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.temperature_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float GeoWeatherGate::temperature() const {
  // @@protoc_insertion_point(field_get:GeoWeatherGate.temperature)
  return _internal_temperature();
}
inline void GeoWeatherGate::set_temperature(float value) {
  _internal_set_temperature(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:GeoWeatherGate.temperature)
}
inline float GeoWeatherGate::_internal_temperature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.temperature_;
}
inline void GeoWeatherGate::_internal_set_temperature(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.temperature_ = value;
}

// float humidity = 2;
inline void GeoWeatherGate::clear_humidity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.humidity_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline float GeoWeatherGate::humidity() const {
  // @@protoc_insertion_point(field_get:GeoWeatherGate.humidity)
  return _internal_humidity();
}
inline void GeoWeatherGate::set_humidity(float value) {
  _internal_set_humidity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:GeoWeatherGate.humidity)
}
inline float GeoWeatherGate::_internal_humidity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.humidity_;
}
inline void GeoWeatherGate::_internal_set_humidity(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.humidity_ = value;
}

// float pressure = 3;
inline void GeoWeatherGate::clear_pressure() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pressure_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline float GeoWeatherGate::pressure() const {
  // @@protoc_insertion_point(field_get:GeoWeatherGate.pressure)
  return _internal_pressure();
}
inline void GeoWeatherGate::set_pressure(float value) {
  _internal_set_pressure(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:GeoWeatherGate.pressure)
}
inline float GeoWeatherGate::_internal_pressure() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pressure_;
}
inline void GeoWeatherGate::_internal_set_pressure(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pressure_ = value;
}

// int64 timestamp = 4;
inline void GeoWeatherGate::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int64_t GeoWeatherGate::timestamp() const {
  // @@protoc_insertion_point(field_get:GeoWeatherGate.timestamp)
  return _internal_timestamp();
}
inline void GeoWeatherGate::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:GeoWeatherGate.timestamp)
}
inline ::int64_t GeoWeatherGate::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void GeoWeatherGate::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// string sensor_id = 5;
inline void GeoWeatherGate::clear_sensor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sensor_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& GeoWeatherGate::sensor_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GeoWeatherGate.sensor_id)
  return _internal_sensor_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GeoWeatherGate::set_sensor_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.sensor_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GeoWeatherGate.sensor_id)
}
inline ::std::string* PROTOBUF_NONNULL GeoWeatherGate::mutable_sensor_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_sensor_id();
  // @@protoc_insertion_point(field_mutable:GeoWeatherGate.sensor_id)
  return _s;
}
inline const ::std::string& GeoWeatherGate::_internal_sensor_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sensor_id_.Get();
}
inline void GeoWeatherGate::_internal_set_sensor_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sensor_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GeoWeatherGate::_internal_mutable_sensor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sensor_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GeoWeatherGate::release_sensor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GeoWeatherGate.sensor_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.sensor_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sensor_id_.Set("", GetArena());
  }
  return released;
}
inline void GeoWeatherGate::set_allocated_sensor_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.sensor_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sensor_id_.IsDefault()) {
    _impl_.sensor_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GeoWeatherGate.sensor_id)
}

// bytes entry_hash = 6;
inline void GeoWeatherGate::clear_entry_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entry_hash_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& GeoWeatherGate::entry_hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GeoWeatherGate.entry_hash)
  return _internal_entry_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GeoWeatherGate::set_entry_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.entry_hash_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GeoWeatherGate.entry_hash)
}
inline ::std::string* PROTOBUF_NONNULL GeoWeatherGate::mutable_entry_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_entry_hash();
  // @@protoc_insertion_point(field_mutable:GeoWeatherGate.entry_hash)
  return _s;
}
inline const ::std::string& GeoWeatherGate::_internal_entry_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entry_hash_.Get();
}
inline void GeoWeatherGate::_internal_set_entry_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entry_hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GeoWeatherGate::_internal_mutable_entry_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.entry_hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GeoWeatherGate::release_entry_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GeoWeatherGate.entry_hash)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.entry_hash_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.entry_hash_.Set("", GetArena());
  }
  return released;
}
inline void GeoWeatherGate::set_allocated_entry_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.entry_hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.entry_hash_.IsDefault()) {
    _impl_.entry_hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GeoWeatherGate.entry_hash)
}

// -------------------------------------------------------------------

// TrinityLedger

// repeated .GeoWeatherGate weather_data = 1;
inline int TrinityLedger::_internal_weather_data_size() const {
  return _internal_weather_data().size();
}
inline int TrinityLedger::weather_data_size() const {
  return _internal_weather_data_size();
}
inline void TrinityLedger::clear_weather_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weather_data_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::GeoWeatherGate* PROTOBUF_NONNULL TrinityLedger::mutable_weather_data(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:TrinityLedger.weather_data)
  return _internal_mutable_weather_data()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>* PROTOBUF_NONNULL TrinityLedger::mutable_weather_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:TrinityLedger.weather_data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_weather_data();
}
inline const ::GeoWeatherGate& TrinityLedger::weather_data(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TrinityLedger.weather_data)
  return _internal_weather_data().Get(index);
}
inline ::GeoWeatherGate* PROTOBUF_NONNULL TrinityLedger::add_weather_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::GeoWeatherGate* _add =
      _internal_mutable_weather_data()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:TrinityLedger.weather_data)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>& TrinityLedger::weather_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:TrinityLedger.weather_data)
  return _internal_weather_data();
}
inline const ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>&
TrinityLedger::_internal_weather_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.weather_data_;
}
inline ::google::protobuf::RepeatedPtrField<::GeoWeatherGate>* PROTOBUF_NONNULL
TrinityLedger::_internal_mutable_weather_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.weather_data_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // trinity_2eproto_2epb_2eh
